version: 0.2

#env:
  #  variables:
    #    DOCKER_BUILDKIT: "1"

phases:
  pre_build:
    commands:
        #- export AWS_CONFIG_FILE=config
        #
        #    nora
        #      - $(aws ecr get-login --registry-ids ${REGISTRY_IDS} --no-include-email --profile prd-account-role)
        #      - REPOSITORY_URI=${REGISTRY_IDS}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_NAME}
        #      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION}
        #
        # initial-server
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
        #- IMAGE_TAG=$CODEBUILD_RESOLVED_SOURCE_VERSION
  build:
    commands:
      - docker build -t 247302787221.dkr.ecr.us-east-1.amazonaws.com/qz-edge-api:latest .
      - docker push 247302787221.dkr.ecr.us-east-1.amazonaws.com/qz-edge-api:latest
  post_build:
    commands:
      - docker tag 247302787221.dkr.ecr.us-east-1.amazonaws.com/qz-edge-api:latest 644426536299.dkr.ecr.us-east-1.amazonaws.com/qz-edge-api:latest
      - $(aws ecr get-login --registry-ids 644426536299 --no-include-email --region $AWS_DEFAULT_REGION)
      - docker push 644426536299.dkr.ecr.us-east-1.amazonaws.com/qz-edge-api:latest
      #       - docker push 247302787221.dkr.ecr.us-east-1.amazonaws.com/initial-server-api:$IMAGE_TAG 
      # - docker push 247302787221.dkr.ecr.us-east-1.amazonaws.com/initial-server-batch:$IMAGE_TAG
      #- docker push 247302787221.dkr.ecr.us-east-1.amazonaws.com/crunchbase/daily-report-fetcher:$IMAGE_TAG
      - printf '{"Version":"1.0","ImageURI":"%s"}' 247302787221.dkr.ecr.us-east-1.amazonaws.com/initial-server-api:latest > imageDetail.json
artifacts:
  files:
    - imageDetail.json
    - taskdef.json
    - appspec.yml
